apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: kafka
spec:
  ports:
  - name: "zookeeper"
    port: 2181
    targetPort: 2181
  - name: "web-ui"
    port: 3030
    targetPort: 3030
  - name: "schema-registry"
    port: 8081
    targetPort: 8081
  - name: "kafka-rest-proxy"
    port: 8082
    targetPort: 8082
  - name: "kafka-connect-distributed"
    port: 8083
    targetPort: 8083
  - name: "kafka-broker"
    port: 9092
    targetPort: 9092
  selector:
    app: kafka