apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-data
  name: kafka-data
  namespace: kafka
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
