apiVersion: v1
kind: Service
metadata:
  labels:
    app: word-count
  name: word-count
  namespace: word-count
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: word-count
  type: ClusterIP
